[package]
name = "zicket"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.62.1"
assert_macros = "2.14.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
